---
title: "Notatniczek"
author: "Wiktor Warchałowski"
date: "4/26/2022"
output: html_document
---
```{r include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(gt)
library(tinytex)
library(officer)
library(huxtable)
```
```{r, include=FALSE}
wyniki1 <- read_csv("kwestionariusz.csv")
```
```{r, include=FALSE}
wyniki <- wyniki1 %>%
  rename(time = `Sygnatura czasowa`,
         approval = `Potwierdzam, że ukończyłam 18 lat i wyrażam zgodę na udział w badaniu`,
         gender = `Proszę podać swoją płeć.`,
         age = `Proszę podać swój wiek w latach.`,
         town = `Proszę podać wielkość miejsca zamieszkania`,
         student = `Czy aktualnie studiujesz/uczysz się?`,
         ig_account = `Czy posiadasz konto na platformie Instagram?`,
         Publikowanie = `Jeśli masz konto na platformie Instagram to czy udostępniasz na niej zdjęcia swojego wizerunku?`,
         P1 = `Szanuję swoje ciało`,
         P2 = `Czuję się dobrze ze swoim ciałem`,
         P3 = `Uważam, że moje ciało ma przynajmniej kilka zalet`,
         P4 = `Mam pozytywny stosunek do swojego ciała`,
         P5 = `Zwracam uwagę na potrzeby swojego ciała`,
         P6 = `Kocham swoje ciało`,
         P7 = `Cenię odmienne i niepowtarzalne cechy swojego ciała`,
         P8 = `Moje zachowanie wyraża mój pozytywny stosunek do mojego ciała; na przykład chodzę z podniesioną głową i uśmiecham się`,
         P9 = `Czuję się komfortowo w swoim ciele`,
         P10 = `Czuję się piękny/-a, nawet jeśli wyglądam inaczej niż atrakcyjne osoby prezentowane w mediach (np. modele/modelki, aktorzy/aktorki)`,
         Modyfikacja = `Czy kiedykolwiek, w jakikolwiek sposób zmodyfikowałaś zdjęcie swojego wizerunku na platformie Instagram tak, aby prezentować się na nim lepiej (prosimy o nieuwzględnianie filtrów, które jedynie zmieniają kolory na zdjęciach)?`,
         truth = `Na wszystkie powyższe pytania odpowiedziałam zgodnie z prawdą i wyrażam zgodę na użycie ich w analizie wyników badania.`)
```
```{r, include=FALSE}
wyniki <- wyniki %>%
  mutate(pretty_timestamp = ymd_hms(time))
```

```{r, include=FALSE}
sumy <- wyniki %>%
  mutate(Suma = P1+P2+P3+P4+P5+P6+P7+P8+P9+P10)
```

```{r, include=FALSE}
filtr <- sumy[!(sumy$gender == "Mężczyzna" | sumy$gender == "Inna"),]
filtr2 <- filtr[!(filtr$ig_account == "Nie"),]
filtr1 <- filtr2[!(filtr2$Modyfikacja == "Nie publikuję swoich zdjęć na platformie Instagram"),]
```

```{r}
ost <- filtr1 %>%
  select(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, Suma, Modyfikacja)
mean((ost %>% filter(Modyfikacja=="Tak"))$Suma)
```

```{r}
ggplot(ost) +
  geom_histogram(aes(x = Suma), binwidth = 5)
```

```{r}
tabelka <- hux(ost)
tabelka %>%
  set_bold(1, everywhere)             %>%
  set_bottom_border(1, everywhere)    %>%
  set_align(everywhere, 2, 'right')   %>%
  set_lr_padding(10)                  %>%
  set_width(1)                        %>%
  set_number_format(0)                %>%
  set_caption("Wyniki surowe")
```